- name: http
  package:
    name: httpie
    state: latest

- name: install HAProxy
  yum:
    name: haproxy
    state: latest

- name: enable HAProxy
  service:
    name: haproxy
    enabled: true

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: restart HAproxy
  service:
    name: haproxy
    state: restarted
