#Base Config
- name: Base Config
  hosts: all
  gather_facts: no
  become: true
  roles:
    - { role: base_setup }
  # tags:
  #   - base

#Setup Front End
- name: Setup Front-end
  hosts: frontends
  gather_facts: no
  become: true
  roles:
    - { role: frontends }

#Setup Apps
- name: Setup Front-end
  hosts: apps
  gather_facts: no
  become: true
  roles:
    - { role: apps }


#Setup database - postgresql
- name: Setup the Database
  hosts: appdbs
  gather_facts: true
  become: true
  roles:
    - { role: geerlingguy.postgresql}
